### ISSUE TITLE
ModuleNotFoundError: No module named 'PfsenseFauxapi'

### ISSUE THREAD

**Issue by burntoc** [dgshue/home-assistant-custom-components#3]
If this is something I configured - my apologies, but I don't recall using this string and it doesn't appear in my configuration.yaml, my manifest.json, or in my FauxAPI keys.....

Error while setting up platform pfsense_rule
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/pfsense_rule/switch.py", line 60, in setup_platform
    from PfsenseFauxapi.PfsenseFauxapi import PfsenseFauxapi
ModuleNotFoundError: No module named 'PfsenseFauxapi'

**Comment by dgshue** [comment]
Try pulling down the manifest again.. added the python library to the manifest.

**Comment by travisghansen** [comment]
Implemented this and many other features over here: https://github.com/travisghansen/hass-pfsense

Looking for feedback and collaboration!
