### ISSUE TITLE
Doesn't appear to work anymore

### ISSUE THREAD

**Issue by crag-r** [dgshue/home-assistant-custom-components#6]
Posted on the thread on Home-Assistant.io thread but raising it here too.

Long story short.

fauxapi works fine from my MacBook, can pull the config through, rules etc so the key and secret are correct.
HomeAssistant pulls the rule through as a switch OK even though there are loads of errors in the log showing
```
Problem retrieving rule set from pfSense host: X.X.X.X. Likely due to API key or secret.
```

The switch doesn't work though, soon as you toggle it you get an error which is as follows;

```
'tracker'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 621, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/pfsense_rule/switch.py", line 126, in turn_on
    self.set_rule_state(True)
  File "/config/custom_components/pfsense_rule/switch.py", line 171, in set_rule_state
    if (rule['tracker'] == self._tracker_id):
KeyError: 'tracker'
```

Am I missing something obvious? 

No error logs on the pfSense host either.

Running the following;
Home Assistant 0.112.4
pfSense 2.4.5-RELEASE-p1

**Comment by burntoc** [comment]
There's some info [here](https://community.home-assistant.io/t/pfsense-rule-switch/109424/9) that may help you get it working again.  It fixed my issue after mine stopped working.

**Comment by travisghansen** [comment]
Implemented this and many other features over here: https://github.com/travisghansen/hass-pfsense

fauxapi not required.

Looking for feedback and collaboration!
